version: '3.8'
services:
  server:
    build: .
    command: pnpm run server
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    ports:
      - "4000:4000"

  dev:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - .:/app
    command: >
      sh -c "HOST=$${HOST} PORT=$${PORT} pnpm run dev"
